### ISSUE TITLE
"Please help us cut down on flakes by" dead link

### ISSUE THREAD

**Issue by e-minguez** [openshift/ci-tools#1004]
* https://github.com/openshift/ci-tools/blob/master/test/integration/pj-rehearse/master/core-services/prow/02_config/_config.yaml#L5
* https://github.com/openshift/ci-tools/blob/master/test/integration/pj-rehearse/candidate/core-services/prow/02_config/_config.yaml#L5
* https://github.com/openshift/ci-tools/blob/master/test/integration/cvp-trigger/config.yaml#L4

Those point to https://github.com/kubernetes/community/blob/master/contributors/devel/flaky-tests.md#filing-issues-for-flaky-tests which doesn't exist.

**Comment by petr-muller** [comment]
Thanks! I wonder how useful that sentence actually is. Maybe we should just remove it?
