### ISSUE TITLE
Cannot use repo-brancher to fast forward our code

### ISSUE THREAD

**Issue by skeeey** [openshift/ci-tools#1118]
We want to use `repo-brancher` tool to fast forward our code from master to our release branch (out job can be found [here]( https://github.com/openshift/release/blob/master/ci-operator/jobs/open-cluster-management/registration/open-cluster-management-registration-master-postsubmits.yaml#L24)), but because our promotion [namespace](https://github.com/openshift/release/blob/master/ci-operator/config/open-cluster-management/registration/open-cluster-management-registration-master.yaml#L18) is not the `ocp`, the `repo-brancher` will be failed to check from https://github.com/openshift/ci-tools/blob/master/pkg/promotion/promotion.go#L39, from `repo-brancher` code, I found the promotion namespace is a const var (https://github.com/openshift/ci-tools/blob/master/pkg/promotion/promotion.go#L15)

Can we add a `PromotionNamespace` option for `repo-brancher` [`Options`](https://github.com/openshift/ci-tools/blob/master/pkg/promotion/promotion.go#L108), if the `PromotionNamespace` option is not specified, `repo-brancher` will run the current logic, if the `PromotionNamespace` option is specified, we will check the promotion namespace option whether matches with the `configuration.PromotionConfiguration.Namespace`, the code maybe

```go
func (o *Options) matches(configuration *cioperatorapi.ReleaseBuildConfiguration) bool {
        if !isDisabled(configSpec) {
              return false
        }
        promotionNamespace := extractPromotionNamespace(configSpec)
        if o.PromotionNamesapce != "" {
          return promotionNamespace == o.PromotionNamesapce && configuration.PromotionConfiguration.Name == o.CurrentRelease
        }
        promotionName := extractPromotionName(configSpec)
	return RefersToOfficialImage(promotionName, promotionNamespace) && configuration.PromotionConfiguration.Name == o.CurrentRelease
}
```

any comments?

**Comment by alvaroaleman** [comment]
This was fixed in #1125 
/close
