### ISSUE TITLE
Typo in headline of patches generated by ocp-build-data-enforcer

### ISSUE THREAD

**Issue by zaneb** [openshift/ci-tools#1152]
https://github.com/openshift/ci-tools/blob/f34cc5951cb5c80b3a732f5df38d11a5503e3b4c/cmd/ocp-build-data-enforcer/main.go#L291

match?

**Comment by stevekuznetsov** [comment]
Seems like this was fixed!

/close

**Comment by zaneb** [comment]
> Seems like this was fixed!

No it doesn't:

https://github.com/openshift/ci-tools/blob/1c2f067fdd235f5aff2caca9fe87340543f193d0/cmd/ocp-build-data-enforcer/main.go#L292

/reopen
