### ISSUE TITLE
Logs are not collected when the job is canceled because of a timeout

### ISSUE THREAD

**Issue by gbenhaim** [openshift/ci-tools#1340]
For example in https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/13120/rehearse-13120-pull-ci-openshift-metal3-dev-scripts-master-e2e-metal-ipi-upgrade/1321109185345097728

The `baremetalds-e2e-test` was canceled because of a timeout. The artifacts directory of the step doesn't exist in the artifacts of the job https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/13120/rehearse-13120-pull-ci-openshift-metal3-dev-scripts-master-e2e-metal-ipi-upgrade/1321109185345097728/artifacts/e2e-metal-ipi-upgrade/

cc @andfasano

**Comment by petr-muller** [comment]
Tracked in https://issues.redhat.com/browse/DPTP-1683
