### ISSUE TITLE
pj-rehearse did not create CM for new template

### ISSUE THREAD

**Issue by petr-muller** [openshift/ci-tools#136]
https://github.com/openshift/release/pull/4938 added a new job together with a new template used by this new job. The rehearsal created for this job got stuck on failing to mount the template CM:

```
MountVolume.SetUp failed for volume "job-definition" : configmaps "rehearse-template-cluster-launch-installer-ipi-e2e-dd409aae" not found
```

The pj-rehearse output suggests that the CM was not even created:

```
time="2019-09-12T16:19:57Z" level=info msg="Rehearsing Prow jobs for a configuration PR" pr=4938
time="2019-09-12T16:20:00Z" level=info msg="templates changed" pr=4938 templates="[{ci-operator/templates/openshift/installer/cluster-launch-installer-ipi-e2e.yaml dd409aae952175ffec1a2c6f38822f919a85e1ab}]"
time="2019-09-12T16:20:00Z" level=info msg="Job has been chosen for rehearsal" diffs=" .Agent:   a: ''   b: 'kubernetes'" job-name=pull-ci-openshift-installer-master-e2e-ipi pr=4938 repo=openshift/installer
time="2019-09-12T16:20:00Z" level=info msg="Created a rehearsal job to be submitted" pr=4938 rehearsal-job=rehearse-4938-pull-ci-openshift-installer-master-e2e-ipi target-job=pull-ci-openshift-installer-master-e2e-ipi target-repo=openshift/installer
time="2019-09-12T16:20:00Z" level=info msg="Submitting a new prowjob." job=rehearse-4938-pull-ci-openshift-installer-master-e2e-ipi name=2b7aacd1-d579-11e9-9688-0a58ac100856 org=openshift pr=4938 repo=release type=presubmit
time="2019-09-12T16:20:00Z" level=info msg="Submitted rehearsal prowjob" job=rehearse-4938-pull-ci-openshift-installer-master-e2e-ipi name=2b7aacd1-d579-11e9-9688-0a58ac100856 org=openshift pr=4938 repo=release type=presubmit 
```

I have copied the commit from the problematic PR here for reference:
https://github.com/petr-muller/release/commit/d69407a003cf16106f20fe9a880fdf3e3258cc76

**Comment by bbguimaraes** [comment]
The template needs to be known by `updateconfig`. The manner in which `rehearse` fails is not the clearest, but it at least signals an invalid configuration.

**Comment by petr-muller** [comment]
@bbguimaraes hm, so we do not need `updateconfig` for actually detecting the change (because pj-rehearse detected the template change, see the second line), but we do for creating the CM? We should at least fail better...

**Comment by bbguimaraes** [comment]
Correct, we use `updateconfig` to translate the template files to ConfigMaps. The side effect of a template not being present in the configuration is it not being created.

*Technically*, we reproduce production perfectly, but I agree this is not ideal. It's not even the first time a user finds that "bug".

**Comment by bbguimaraes** [comment]
For reference, this is the relevant code: https://github.com/openshift/ci-tools/blob/3be938fc278158b5af71e72135e7beaa9f7edb4e/pkg/config/template.go#L89-L106.

As I said, this "issue" is just us simulating production, not due to negligence. If we want to add more validation, that would be a whole new layer.

**Comment by petr-muller** [comment]
/close

I think https://github.com/openshift/ci-tools/pull/664 is the fix.
