### ISSUE TITLE
Missing License file.

### ISSUE THREAD

**Issue by kshithijiyer** [openshift/ci-tools#18]

**Comment by bbguimaraes** [comment]
We didn't even have them in the [old](https://github.com/openshift/ci-operator) [repositories](https://github.com/openshift/ci-operator-prowgen). I guess we should just add the same as [upstream](https://github.com/kubernetes/test-infra/blob/master/LICENSE) (and [origin](https://github.com/openshift/origin/blob/master/LICENSE)).
