### ISSUE TITLE
How does CI decide that a test has failed?

### ISSUE THREAD

**Issue by vimalk78** [openshift/ci-tools#1801]
Many times i have observed CI has failed a test for no actual test case failing.  I suspect if CI finds certain keywords lile `error` or `time out` etc, then also the test case fails.
Specifically can you point out why this test case has failed? https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-logging-operator/934/pull-ci-openshift-cluster-logging-operator-master-e2e-operator/1372384244810125312

**Comment by vimalk78** [comment]
another failure
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-logging-operator/934/pull-ci-openshift-cluster-logging-operator-master-e2e-operator/1372422240557076480

**Comment by petr-muller** [comment]
It's simply a matter of the configured command returning a non-zero RC, nothing else. 

https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-logging-operator/934/pull-ci-openshift-cluster-logging-operator-master-e2e-operator/1372384244810125312#1:build-log.txt%3A12464

/close

Please reach out to `@dptp-helpdesk` on `#forum-testplatform` Slack channel with further questions.
