### ISSUE TITLE
Job Search Page: Expose job type & optional

### ISSUE THREAD

**Issue by YuviGold** [openshift/ci-tools#2361]
Currently, there's no way to see which jobs are mandatory and which not, unless going to a repository config file or on a PR commenting with `/test ?`.

It would be nice to have all this information centralized in one place.
Show on https://steps.ci.openshift.org/search the type of the jobs (periodic, presubmit) and if the job is optional.

**Comment by petr-muller** [comment]
/close

Moved to https://issues.redhat.com/browse/DPTP-2513 
Please file DPTP cards instead of GH issues, we don't use GH issues to track any work.
