### ISSUE TITLE
Target Version calculation seems off for 4.10.0 in BZ backporter

### ISSUE THREAD

**Issue by haircommander** [openshift/ci-tools#2363]
I have a bug that is targeted at 4.10.0, and I am attempting to use BZ backporter to backport it to relevant branches. Unfortunately, I am only able to see 4.1.z and 3.11.z as options. 

ref https://bugs.ci.openshift.org/clones?ID=2002434

**Comment by petr-muller** [comment]
Tracked in https://issues.redhat.com/browse/DPTP-2524
