### ISSUE TITLE
Default artifact PR broke test-specific secrets

### ISSUE THREAD

**Issue by petr-muller** [openshift/ci-tools#294]
We needed to [revert](https://github.com/openshift/ci-tools/pull/293) the PR for [Default artifacts directory, set env](https://github.com/openshift/ci-tools/pull/286) because of reported breakage of some Prow jobs.

Example: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/periodic-ci-openshift-osde2e-master-e2e-prod-4.2/78

The reason is likely the interaction with the test-specific `secret:` stanza in ci-operator config.

I'm attaching different outputs of ci-operator (revision a7bff0511055b701bc9d40dc1e8ce32df208cd07, before revert) local execution:

`ci-operator --git-ref openshift/osde2e@master --config $OSRELEASE/ci-operator/config/openshift/osde2e/openshift-osde2e-master.yaml --target=e2e-prod-4.2 --artifact-dir /tmp --dry-run`

/assign @stevekuznetsov

**Comment by petr-muller** [comment]
[without-secret.txt](https://github.com/openshift/ci-tools/files/3875949/without-secret.txt)
[with-secret.txt](https://github.com/openshift/ci-tools/files/3875950/with-secret.txt)

The `with-secret` is notably missing the artifacts volume.

**Comment by bbguimaraes** [comment]
https://github.com/openshift/ci-tools/blob/9d77c7c37ec69ddf72f863ebbef09d770bd04950/pkg/steps/pod.go#L237-L240

…
