### ISSUE TITLE
pr-reminder: detect new commits

### ISSUE THREAD

**Issue by jsafrane** [openshift/ci-tools#3079]
We in OCP storage team use cmd/pr-reminder and I'd appreciate if a PR age was not counted since the PR was created, but since it got a new comment, label, new title, new push / force-push or similar activity. It happens to me that I'm waiting for review comments to be addressed in several PRs, they get orange / red and I tend to ignore them. I then miss a new comment or a new commit. It does not need to get green, any other form of visible emphasis would be enough.

@psalajova, what do you think?

**Comment by jsafrane** [comment]
cc @smg247 who wrote the tool.

**Comment by smg247** [comment]
@jsafrane, the PRs in the digest are ordered by most recent update (comment, label, title, push, etc..) first. It also includes the time and date of the most recent update. The colored circles are just there to remind users of how old the PR is, with the hope that older PRs will be addressed more urgently as the author has been waiting longer to merge it.

I am open to new ideas for this tool, however. Maybe another visual indicator can be added to it if it was updated within the last day? Thoughts?

**Comment by jsafrane** [comment]
Sorry, I missed the "Updated" date, it's so small :-)
/close
