### ISSUE TITLE
The bot that clones the jira tickets while backporting should maintain the assignee field

### ISSUE THREAD

**Issue by harche** [openshift/ci-tools#3203]
The bot that clones the jira tickets while backporting should maintain the assignee field. e.g https://issues.redhat.com/browse/OCPBUGS-4805 is a clone of https://issues.redhat.com/browse/OCPBUGS-4101. If the assignee  field is not maintained then it slips out of original assignee's list of bugs and could potentially get lost.

**Comment by droslean** [comment]
This is related to https://github.com/openshift-eng/jira-lifecycle-plugin

/close
