### ISSUE TITLE
Why those 3 jobs are not rehearsed?

### ISSUE THREAD

**Issue by hongkailiu** [openshift/ci-tools#339]
https://github.com/openshift/release/pull/6331

Those 3 jobs are with rehearse label:

* pull-ci-openshift-origin-master-e2e-aws-fips
* pull-ci-openshift-origin-master-e2e-aws-multitenant
* pull-ci-openshift-origin-master-e2e-aws-ovn

But they are not rehearsed.

They should be since we have changed the config file with the `cluster` params.

**Comment by petr-muller** [comment]
I wondered about the same while I was working on the `openshift-priv` fork of origin:

This ci-operator config change triggered only 4 rehearsals: https://github.com/openshift/release/pull/6476
This PR which changed the jobs themselves, too: https://github.com/openshift/release/pull/6448

**Comment by hongkailiu** [comment]
Some feeling:

1. the relevant function:

https://github.com/openshift/ci-tools/blob/7508b9ecfafddcfc704eeef5f166656d15f7dece/cmd/pj-rehearse/main.go#L280

2. it relies on how we collect `affectedJobs`:

https://github.com/openshift/ci-tools/blob/7508b9ecfafddcfc704eeef5f166656d15f7dece/cmd/pj-rehearse/main.go#L181-L184

The function above seems considering only the tests from config files and that explains why the 3 tests are not rehearsed.

**Comment by hongkailiu** [comment]
@petr-muller 
I still cannot explain why there were missing rehearsals. It seems all the tests in `priv` repo are from the config.

**Comment by hongkailiu** [comment]
Fixed by https://github.com/openshift/ci-tools/pull/351

<img width="747" alt="Screen Shot 2020-01-13 at 9 26 12 AM" src="https://user-images.githubusercontent.com/4013349/72263435-da556080-35e6-11ea-9ef3-6d78d78875e7.png">

/close
