### ISSUE TITLE
Multi-secrets leads to a duplicate secret name error

### ISSUE THREAD

**Issue by meowfaceman** [openshift/ci-tools#342]
Example: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/6519/rehearse-6519-periodic-ci-openshift-osde2e-master-addon-prow-operator-test/2

When using multi-secrets, at least in a rehearsal, the job fails with:
```
failed to create or restart test pod: unable to create pod: Pod "addon-prow-operator-test" is invalid: spec.volumes[2].name: Duplicate value: "test-secret"
```

Despite the fact that the job yaml doesn't reference this. For the moment it makes the multi-secret support unusable.

**Comment by jeefy** [comment]
This appears to be a flake. Haven't been able to reproduce the event and was likely something wrong with Prow at the time. Closing this out as things seem happy. :) 

/close
