### ISSUE TITLE
PROW CI should support send Job status to multiple Slack channel

### ISSUE THREAD

**Issue by LiZhang19817** [openshift/ci-tools#3477]
Hi CI Operator team,

Now Openshift Quay QE team and Openshift InterOP teams have a requirement to send the test report to multiple Slack channel, pls give support.

**PROW CI Docs**: https://docs.ci.openshift.org/docs/how-tos/notification/

**Example:**
```
`reporter_config:
    slack:
      channel: 
      - '#quay-qe1'
      - '#quay-qe2'
      - '#quay-qe3'
      job_states_to_report:
      - success
      - failure
      - error
      report_template: '{{if eq .Status.State "success"}} :rainbow: Job *{{.Spec.Job}}*
        ended with *{{.Status.State}}*. <{{.Status.URL}}|View logs> :rainbow: {{else}}
        :volcano: Job *{{.Spec.Job}}* ended with *{{.Status.State}}*. <{{.Status.URL}}|View
        logs> :volcano: {{end}}'`
```

**Comment by smg247** [comment]
@LiZhang19817 we don't use github issues to track bugs or enhancements. In the future, please use the workflows in the `#forum-testplatform` slack channel. This one, specifically, is actually an upstream feature. The issue should be filed in https://github.com/kubernetes/test-infra
/close
