### ISSUE TITLE
CONTRIBUTING.md L31 leads to a dead/404 Tide README.md url

### ISSUE THREAD

**Issue by tshefi** [openshift/ci-tools#4064]
I'd suggest a fix myself for the dead link [here](https://github.com/openshift/ci-tools/blob/master/CONTRIBUTING.md?plain=1#L31), but I only just started learning things. 
Also noticed this [commit](https://github.com/kubernetes/test-infra/commit/f043197927e03e62b8101273fad5bbaf192aeb3f#diff-bcff479369298a462be97c0184f4b96adea18fe655f0e5108cbf9fabcadec32b), which may be related.

**Comment by smg247** [comment]
@tshefi Test Platform doesn't use GH issues for bug reports or feature requests. Assuming this is still valid, please use the proper workflow in the `#forum-ocp-testplatform` slack channel to file a card.

/close
