### ISSUE TITLE
ci-tools overwrites env `GOPATH` of images built with `from:`

### ISSUE THREAD

**Issue by kaovilai** [openshift/ci-tools#4165]
The diff between [failed job](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_oadp-operator/1416/pull-ci-openshift-oadp-operator-master-4.14-images/1799082990651838464)
and [success](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_oadp-operator/1416/pull-ci-openshift-oadp-operator-master-4.14-images/1799093815051554816) is [removing `from:` statement](https://github.com/openshift/release/pull/52952) which I'm suspecting is coming from
https://github.com/openshift/ci-tools/blame/master/pkg/steps/source.go#L102C5-L102C5
https://github.com/openshift/ci-tools/blame/2db1b19e7a50e0b8fb690ad2ba7757f961792168/pkg/steps/source.go#L102C5-L102C5

**Comment by smg247** [comment]
@kaovilai Test Platform doesn't use GH issues for bug reports or feature requests. Assuming this is still valid, please use the proper workflow in the `#forum-ocp-testplatform` slack channel to file a card.

/close

**Comment by kaovilai** [comment]
https://issues.redhat.com/browse/DPTP-4099
