### ISSUE TITLE
Getting cloneref for non-amd64 archs

### ISSUE THREAD

**Issue by Pensu** [openshift/ci-tools#57]
Hi,

The cloneref binary is required to run the test cases in prow and is added to the environment in the ci-tools source here: https://github.com/openshift/ci-tools/blob/bcb9b448ade82bdd00a458bcfecbb2f762243a7c/pkg/steps/source.go#L69

Now, this comes from an amd64 image, and doesn't work for non-amd64 archs. To run it on a multi-arch environment, there could be a workaround to get the `cloneref` binary using `go get`. I have been able to run cloneref using `go get k8s.io/test-infra/prow/cmd/clonerefs` on a ppc64le system.

Would it be a right solution to enable ci-tools to run on multi-arch systems? Or should there be another way to support non-amd64 archs? Thanks.

**Comment by mkumatag** [comment]
Currently, this binary has been fetched from `gcr.io/k8s-prow/clonerefs` image from `/app/prow/cmd/clonerefs/app.binary.runfiles/io_k8s_test_infra/prow/cmd/clonerefs/linux_amd64_pure_stripped` location, I'm wondering whether we can enhance `bazel build` script in `k/test-infra` project to build app binaries for multiple architectures and ship it within the prow images or can we just build one `ci-tool/infra` image and keep all possible prereq tool needed for different architectures for builds meanwhile?

@stevekuznetsov what do you say?

**Comment by stevekuznetsov** [comment]
I think it's a good question for the `kubernetes/test-infra` repo and @fejta in particular, is there an RBE for Bazel that would allow `test-infra` to publish mutli-arch images?

**Comment by fejta** [comment]
Depends on https://github.com/bazelbuild/rules_docker/issues/300
