### ISSUE TITLE
Use simpler container names and conventions in step registry

### ISSUE THREAD

**Issue by smarterclayton** [openshift/ci-tools#633]
When launching a pod that is a step name subset (so `<JOB_PREFIX>-<STEP_NAME>`) we can omit duplicating `<STEP_NAME>` in the container, which reduces annoyances getting into those steps and debugging them (and puts some consistency in place).  We should probably have conventions for the container name, but `setup`, `teardown`, and `test` are all good conventions (i.e. what we use right now in the template).  Pre and post are setup and teardown, test is anything in the middle.  

We should also make sure that when the step registry is launching a pod the "user facing" pod is first in the containers list, which makes `rsh`, `rsync`, `exec`, `log` and other commands happier (simplifies debugging).

We're going to have to annotate some of the pods/secrets so that cluster bot can get auth info out, but that can wait (bot basically needs to get at the right container to get the kubeadmin).

**Comment by bbguimaraes** [comment]
@smarterclayton: naming correction here: https://github.com/openshift/ci-tools/pull/666.

We already place the test container first, e.g. (still using the old container names):

```sh
$ curl -sS https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_sriov-network-operator/192/pull-ci-openshift-sriov-network-operator-master-e2e-aws/464/artifacts/build-resources/pods.json \
    | jq -c '
        .items[]
        | select(.metadata.labels|keys|contains(["ci.openshift.io/multi-stage-test"]))
        | [.metadata.name,[.spec.containers[].name]]'
["e2e-aws-gather-audit-logs",["gather-audit-logs","artifacts"]]
["e2e-aws-gather-extra",["gather-extra","artifacts"]]
["e2e-aws-gather-must-gather",["gather-must-gather","artifacts"]]
["e2e-aws-ipi-conf",["ipi-conf","artifacts"]]
["e2e-aws-ipi-conf-aws",["ipi-conf-aws","artifacts"]]
["e2e-aws-ipi-deprovision-deprovision",["ipi-deprovision-deprovision","artifacts"]]
["e2e-aws-ipi-install-install",["ipi-install-install","artifacts"]]
["e2e-aws-ipi-install-rbac",["ipi-install-rbac","artifacts"]]
["e2e-aws-origin-e2e-test",["origin-e2e-test","artifacts"]]
```

`exec/rsh` already work correctly without the `--container` argument. `logs` does not seem to default to the first container even in regular container tests:

```
$ oc -n ci-op-xkxztsyi logs unit
Error from server (BadRequest): a container name must be specified for pod unit, choose one of: [test artifacts]
```
