### ISSUE TITLE
Template change didn't auto-trigger rehearsal of annotated job

### ISSUE THREAD

**Issue by jaypoulz** [openshift/ci-tools#647]
So Clayton and I were looking at https://github.com/openshift/release/pull/8154. After making a few small edits, the only code left in the changeset belonged to the template:
ci-operator/templates/openshift/installer/cluster-launch-installer-remote-libvirt-e2e.yaml

At this point, the job defined here below no longer triggered for rehearsals.
https://github.com/openshift/release/blob/master/ci-operator/jobs/openshift/release/openshift-release-release-4.2-periodics.yaml#L324
Clayton suggested I make sure the rehearsal annotation was present, but as you can see, I have linked in directly above.

I have run into this behavior before, and thought this was expected.
In order to force a run on the job, I left in a dummy variable in interim commit:
https://github.com/openshift/release/commit/c9ef6a28a70a9df524bbc0935a50cd0e3ee16f92

This produced job log:
https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/8154/rehearse-8154-release-openshift-origin-installer-e2e-remote-libvirt-s390x-4.2/7

However, the following commit (with the dummy var removed) (https://github.com/openshift/release/commit/16c4dbfe196baadbd94552941a19e083704bb8c9) did not retrigger this job.

I asked Steve Kuznetsov about this as well, and he linked me to:
https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/8154/pull-ci-openshift-release-master-pj-rehearse/18031#1:build-log.txt%3A15

**Comment by jaypoulz** [comment]
@petr-muller Steve said you might be looking into something related to this.

**Comment by petr-muller** [comment]
@jaypoulz Yeah, I believe I am now working on this exact issue. It is caused by the fact that the job you want to be rehearsed is a periodic, not a presubmit: some indirect changes (like a template change) currently only trigger presubmit rehearses, not periodic ones. I think I will have this fixed soon; thanks for the report, I'll use it for testing!
